# @format
bot:
  ID: '1297644501502005389'
  TOKEN: ''
  PREFIX: '?'
  EMBED_COLOR: '#ff0000'
  OWNERS: ['870179991462236170']
  MONGO: 'mongodb+srv://razexelite11:spekbot@spek.dl9mwva.mongodb.net'
links:
  INVITE: 'https://discord.com/oauth2/authorize?client_id=1297644501502005389&permissions=8&scope=applications.commands%20bot'
  SUPPORT: 'https://discord.gg/rvSGGKsUBk'
  VOTE: 'https://top.gg/bot/1297644501502005389/vote'
